=== thanosmp/ZooPark/zoo_park_new2.dtd
<!-- Ρίζα του εγγράφου: Στοιχεία του ζωολογικού κήπου -->
<!ELEMENT zoo_park (trainer_list, animal_classification, classification, contact_details, park_timings, tickets, animal_list)>
<!ATTLIST zoo_park
    name CDATA #REQUIRED
    number_of_Animals CDATA #REQUIRED
    Year_opened CDATA #REQUIRED>

<!-- Λίστα φροντιστών -->
<!ELEMENT trainer_list (trainer+)>
<!ELEMENT trainer (#PCDATA)>
<!ATTLIST trainer 
    id ID #REQUIRED>

<!-- Κατηγοριοποίηση ζώων -->
<!ELEMENT animal_classification (classification_type+)>
<!ELEMENT classification_type (#PCDATA)>
<!ATTLIST classification_type 
    id ID #REQUIRED>

<!-- Κατηγοριοποίηση ζώων με βάση τη διατροφή και τα μικρά -->
<!ELEMENT classification (class+)>
<!ATTLIST classification
    class_id CDATA #REQUIRED
    value CDATA #REQUIRED>
    
<!ELEMENT class ((Herbivores | Carnivores | Omnivorous | Wallets | Spawning | Superior)*)>
<!ATTLIST class
    class_id ID #REQUIRED
    value CDATA #REQUIRED>
    
<!-- Καθορισμός id κατηγοριών -->
<!ELEMENT Herbivores EMPTY>
<!ATTLIST Herbivores id CDATA #REQUIRED>
<!ELEMENT Carnivores EMPTY>
<!ATTLIST Carnivores id CDATA #REQUIRED>
<!ELEMENT Omnivorous EMPTY>
<!ATTLIST Omnivorous id CDATA #REQUIRED>
<!ELEMENT Wallets EMPTY>
<!ATTLIST Wallets id CDATA #REQUIRED>
<!ELEMENT Spawning EMPTY>
<!ATTLIST Spawning id CDATA #REQUIRED>
<!ELEMENT Superior EMPTY>
<!ATTLIST Superior id CDATA #REQUIRED>

<!-- Στοιχεία επικοινωνίας κήπου -->
<!ELEMENT contact_details (address, tel, email)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!-- Ωράριο λειτουργίας πάρκου -->
<!ELEMENT park_timings (day+)>
<!ELEMENT day (#PCDATA | timing)*>
<!ATTLIST day
    day_id ID #REQUIRED>
<!ELEMENT timing (#PCDATA)>

<!-- Πληροφορίες εισιτηρίων και χρεώσεων -->
<!ELEMENT tickets (weekday_charges, weekend_holidays_charges)>
<!ELEMENT weekday_charges (w_value*)>
<!ELEMENT w_value (#PCDATA)>
<!ATTLIST w_value
    w_unit CDATA #REQUIRED
    w_ticket_category CDATA #REQUIRED>
<!ELEMENT weekend_holidays_charges (h_value*)>
<!ELEMENT h_value (#PCDATA)>
<!ATTLIST h_value
    h_unit CDATA #REQUIRED
    h_ticket_category CDATA #REQUIRED>

<!-- Λίστα των ζώων του κήπου -->
<!ELEMENT animal_list (animal+)>
<!ELEMENT animal (animal_names_info, trainers, quantity, animal_descr, animal_characteristics, show_participation?, Threats, additional_info)>
<!ATTLIST animal
    animal_id ID #REQUIRED
    an_class_id IDREFS #REQUIRED>

<!-- Ονόματα και ταυτοποίηση ζώου -->
<!ELEMENT animal_names_info EMPTY>
<!ATTLIST animal_names_info
    animal_name CDATA #REQUIRED
    scientific_name CDATA #IMPLIED>

<!-- Σχετιζόμενοι φροντιστές -->
<!ELEMENT trainers EMPTY>
<!ATTLIST trainers
    trainer_id IDREFS #REQUIRED>

<!-- Πληθυσμιακά στοιχεία εντός του κήπου -->
<!ELEMENT quantity (#PCDATA)>

<!-- Περιγραφή του ζώου -->
<!ELEMENT animal_descr (#PCDATA)>

<!-- Βιολογικά χαρακτηριστικά του ζώου -->
<!ELEMENT animal_characteristics (allocation?, weight, habitat, dimensions, lifetime, (pregnancy | incubation), population?)>
<!ELEMENT allocation (#PCDATA)>
<!ELEMENT weight (wmale | wfemale)*>
<!ELEMENT wmale (#PCDATA)>
<!ATTLIST wmale 
    unit_weight CDATA #REQUIRED>
<!ELEMENT wfemale (#PCDATA)>
<!ATTLIST wfemale 
    unit_weight CDATA #REQUIRED>

<!ELEMENT habitat (#PCDATA)>

<!-- Διαστάσεις (Ύψος και Μήκος) -->
<!ELEMENT dimensions (height?, length?)>
<!ELEMENT height (#PCDATA | female)*>
<!ATTLIST height
    unit CDATA #IMPLIED
    max CDATA #IMPLIED
    male CDATA #IMPLIED>
<!ELEMENT length (#PCDATA | female)*>
<!ATTLIST length
    unit CDATA #IMPLIED
    max CDATA #IMPLIED
    male CDATA #IMPLIED>
<!ELEMENT female (#PCDATA)>
<!ATTLIST female
    f_unit_height CDATA #IMPLIED
    f_unit_length CDATA #IMPLIED
    max CDATA #IMPLIED>

<!-- Προσδόκιμο ζωής και αναπαραγωγή -->
<!ELEMENT lifetime (#PCDATA)>
<!ATTLIST lifetime 
    unit CDATA #REQUIRED>

<!ELEMENT pregnancy (#PCDATA)>
<!ATTLIST pregnancy 
    unit CDATA #REQUIRED>

<!ELEMENT incubation (#PCDATA)>
<!ATTLIST incubation 
    unit CDATA #REQUIRED>

<!ELEMENT population (#PCDATA)>

<!-- Συμμετοχή σε εκδηλώσεις και θεάματα -->
<!ELEMENT show_participation ((feeding | trainer_speaking | show_bird_flight | animal_show)*)>
<!ELEMENT feeding (duration, dates)>
<!ELEMENT trainer_speaking (duration, dates)>
<!-- Διάρκεια και ημερομηνίες εκδηλώσεων -->
<!ELEMENT show_bird_flight (duration, dates)>
<!ELEMENT animal_show (duration, dates)>

<!ELEMENT duration (#PCDATA)>
<!ATTLIST duration
    unit CDATA #REQUIRED>

<!ELEMENT dates (date*)>
<!ELEMENT date (#PCDATA)>
<!ATTLIST date
    start_hour CDATA #REQUIRED
    day_id IDREF #REQUIRED>

<!-- Απειλές και κατάσταση διατήρησης (IUCN) -->
<!ELEMENT Threats (threat*)>
<!ATTLIST Threats
    IUCN CDATA #REQUIRED
    indicat_threat CDATA #REQUIRED>
<!ELEMENT threat (#PCDATA)>
<!ATTLIST threat
    threat_id CDATA #REQUIRED>

<!-- Πρόσθετες πληροφορίες και διαδραστικότητα -->
<!ELEMENT additional_info (trainer_accreditation, adoption_program?, animal_image, special_diet?, votes)>

<!-- Πιστοποίηση φροντιστών -->
<!ELEMENT trainer_accreditation EMPTY>
<!ATTLIST trainer_accreditation
    is_accredited (yes | no) #REQUIRED
    accredited_trainers IDREFS #IMPLIED>

<!-- Πρόγραμμα υιοθεσίας ζώου -->
<!ELEMENT adoption_program (gift_ticket?)>
<!ATTLIST adoption_program
    amount CDATA #REQUIRED
    currency CDATA #FIXED "EUR"
    subscription_type (annual | semi-annual) #REQUIRED>
<!ELEMENT gift_ticket (#PCDATA)>

<!-- Φωτογραφικό υλικό -->
<!-- Φωτογραφικό υλικό -->
<!ELEMENT animal_image EMPTY>
<!ATTLIST animal_image
    url CDATA #REQUIRED
    type (jpg | png | gif) #REQUIRED>

<!-- Ειδική διατροφή ή φαρμακευτική αγωγή -->
<!ELEMENT special_diet (diet_item+)>
<!ELEMENT diet_item (#PCDATA)>
<!ATTLIST diet_item
    item_type (food | medicine) #REQUIRED>

<!-- Αξιολογήσεις και ψηφοφορία κοινού -->
<!ELEMENT votes (vote*)>
<!ELEMENT vote (#PCDATA)>
<!ATTLIST vote
    username CDATA #REQUIRED
    stars (1 | 2 | 3 | 4 | 5) #REQUIRED>

=== thanosmp/ZooPark/zoo_park_new2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zoo_park SYSTEM "zoo_park_new2.dtd">
<zoo_park name="WILDLIFE XYZ PARK" number_of_Animals="2000" Year_opened="2000">
    
    <trainer_list>
        <trainer id="T1">George Papadopoulos</trainer>
        <trainer id="T2">Giannis Nemeas</trainer>
        <trainer id="T3">Tzina Eleftheriou</trainer>
        <trainer id="T4">Giorgos Emmanoyilidis</trainer>
        <trainer id="T5">Rafail Psandimon</trainer>
        <trainer id="T6">Maria Popova</trainer>
        <trainer id="T7">Tom Trandon</trainer>
        <trainer id="T8">Jim Paraskevoglou</trainer>
        <trainer id="T9">Chris Boris</trainer>
        <trainer id="T10">Nantia Trejova</trainer>
        <trainer id="T11">Havie Limon</trainer>
        <trainer id="T12">Eva Lampanova</trainer>
    </trainer_list>

    <animal_classification>
        <classification_type id="K1">Αμφίβια</classification_type>
        <classification_type id="K2">Ερπετά</classification_type>
        <classification_type id="K3">Πτηνά</classification_type>
        <classification_type id="K4">Ψάρια</classification_type>
        <classification_type id="K5">Θηλαστικά</classification_type>
    </animal_classification>

    <classification value="ανάλογα με την τροφή" class_id="CLASS_LIST_1">
        <class class_id="C1" value="Φυτοφάγα"/>
        <class class_id="C2" value="Σαρκοφάγα"/>
        <class class_id="C3" value="Παμφάγα"/>
    </classification>

    <contact_details>
        <address>Θέση Γιαλού, Σπάτα 19004</address>
        <tel>2106634724</tel>
        <email>info@atticapark.gr</email>
    </contact_details>

    <park_timings>
        <day day_id="D_WEEK">Καθημερινές<timing>09:00 - 18:30</timing></day>
        <day day_id="D_END">Σαββατοκύριακα<timing>09:00 - 20:00</timing></day>
    </park_timings>

    <tickets>
        <weekday_charges>
            <w_value w_unit="EUR" w_ticket_category="Adult">18</w_value>
            <w_value w_unit="EUR" w_ticket_category="Child">14</w_value>
        </weekday_charges>
        <weekend_holidays_charges>
            <h_value h_unit="EUR" h_ticket_category="Adult">20</h_value>
            <h_value h_unit="EUR" h_ticket_category="Child">15</h_value>
        </weekend_holidays_charges>
    </tickets>

    <animal_list>

        <animal animal_id="A01" an_class_id="K5 C2">
            <animal_names_info animal_name="Λιοντάρι" scientific_name="Panthera leo"/>
            <trainers trainer_id="T1"/>
            <quantity>4</quantity>
            <animal_descr>Το λιοντάρι είναι ένα μεγάλο σαρκοφάγο θηλαστικό της οικογένειας των αιλουριδών.</animal_descr>
            <animal_characteristics>
                <weight><wmale unit_weight="kg">190</wmale><wfemale unit_weight="kg">130</wfemale></weight>
                <habitat>Σαβάνα και ανοιχτές εκτάσεις</habitat>
                <dimensions><height unit="m" max="1.2"/></dimensions>
                <lifetime unit="years">14</lifetime>
                <pregnancy unit="months">4</pregnancy>
            </animal_characteristics>
            <Threats IUCN="Τρωτό" indicat_threat="5">
                <threat threat_id="TH_HUNT">Λαθροθηρία</threat>
            </Threats>
            <additional_info>
                <trainer_accreditation is_accredited="yes" accredited_trainers="T1"/>
                <adoption_program amount="100" subscription_type="annual">
                    <gift_ticket>Εισιτήριο Δώρο για 1 Έτος</gift_ticket>
                </adoption_program>
                <animal_image url="images/lion.jpg" type="jpg"/>
                <special_diet>
                    <diet_item item_type="food">Φρέσκο βόειο κρέας</diet_item>
                </special_diet>
                <votes>
                    <vote username="eleni_98" stars="5">Βασιλιάς του πάρκου!</vote>
                </votes>
            </additional_info>
        </animal>

        <animal animal_id="A02" an_class_id="K5 C1">
            <animal_names_info animal_name="Ασιατικός Ελέφαντας" scientific_name="Elephas maximus"/>
            <trainers trainer_id="T3 T4"/>
            <quantity>2</quantity>
            <animal_descr>Ο ελέφαντας είναι το μεγαλύτερο χερσαίο θηλαστικό στην Ασία.</animal_descr>
            <animal_characteristics>
                <weight><wmale unit_weight="kg">4000</wmale></weight>
                <habitat>Τροπικά δάση και θαμνώδεις εκτάσεις</habitat>
                <dimensions><height unit="m" max="3.0"/></dimensions>
                <lifetime unit="years">60</lifetime>
                <pregnancy unit="months">22</pregnancy>
            </animal_characteristics>
            <Threats IUCN="Κινδυνεύον" indicat_threat="7">
                <threat threat_id="TH_HAB">Απώλεια Βιότοπου</threat>
            </Threats>
            <additional_info>
                <trainer_accreditation is_accredited="yes" accredited_trainers="T3 T4"/>
                <adoption_program amount="150" subscription_type="annual">
                    <gift_ticket>Ετήσιο πάσο υιοθέτη</gift_ticket>
                </adoption_program>
                <animal_image url="images/elephant.jpg" type="jpg"/>
                <votes>
                    <vote username="nikos_p" stars="5">Πολύ έξυπνο ζώο.</vote>
                </votes>
            </additional_info>
        </animal>

        <animal animal_id="A03" an_class_id="K5 C2">
            <animal_names_info animal_name="Τσίτα" scientific_name="Acinonyx jubatus"/>
            <trainers trainer_id="T1 T5"/>
            <quantity>3</quantity>
            <animal_descr>Το ταχύτερο χερσαίο ζώο στον πλανήτη.</animal_descr>
            <animal_characteristics>
                <weight><wmale unit_weight="kg">55</wmale></weight>
                <habitat>Ανοιχτές σαβάνες</habitat>
                <dimensions><length unit="m" max="1.3"/></dimensions>
                <lifetime unit="years">12</lifetime>
                <pregnancy unit="days">93</pregnancy>
            </animal_characteristics>
            <Threats IUCN="Τρωτό" indicat_threat="5">
                <threat threat_id="TH_GEN">Μειωμένη γενετική ποικιλότητα</threat>
            </Threats>
            <additional_info>
                <trainer_accreditation is_accredited="yes" accredited_trainers="T1 T5"/>
                <animal_image url="images/cheetah.png" type="png"/>
                <special_diet>
                    <diet_item item_type="medicine">Βιταμίνες για αρθρώσεις</diet_item>
                </special_diet>
                <votes>
                    <vote username="speedy" stars="4">Απίστευτη ταχύτητα!</vote>
                </votes>
            </additional_info>
        </animal>

        <animal animal_id="A04" an_class_id="K5 C2">
            <animal_names_info animal_name="Ρινοδέλφινο" scientific_name="Tursiops truncatus"/>
            <trainers trainer_id="T6 T7"/>
            <quantity>6</quantity>
            <animal_descr>Θαλάσσιο θηλαστικό με εξαιρετική ευφυΐα και κοινωνικότητα.</animal_descr>
            <animal_characteristics>
                <weight><wmale unit_weight="kg">300</wmale></weight>
                <habitat>Παράκτιες και ανοιχτές θάλασσες</habitat>
                <dimensions><length unit="m" max="3.5"/></dimensions>
                <lifetime unit="years">40</lifetime>
                <pregnancy unit="months">12</pregnancy>
            </animal_characteristics>
            <Threats IUCN="Μειωμένου Ενδιαφέροντος" indicat_threat="2">
                <threat threat_id="TH_NET">Παγίδευση σε δίχτυα</threat>
            </Threats>
            <additional_info>
                <trainer_accreditation is_accredited="yes" accredited_trainers="T6 T7"/>
                <adoption_program amount="80" subscription_type="semi-annual"/>
                <animal_image url="images/dolphin.jpg" type="jpg"/>
                <votes>
                    <vote username="marina" stars="5">Η παρουσίασή τους ήταν μαγική!</vote>
                </votes>
            </additional_info>
        </animal>

        <animal animal_id="A05" an_class_id="K5 C1">
            <animal_names_info animal_name="Καμηλοπάρδαλη" scientific_name="Giraffa camelopardalis"/>
            <trainers trainer_id="T4"/>
            <quantity>5</quantity>
            <animal_descr>Το ψηλότερο ζώο της ξηράς με χαρακτηριστικό μακρύ λαιμό.</animal_descr>
            <animal_characteristics>
                <weight><wmale unit_weight="kg">1200</wmale></weight>
                <habitat>Ξηρές σαβάνες</habitat>
                <dimensions><height unit="m" max="5.5"/></dimensions>
                <lifetime unit="years">25</lifetime>
                <pregnancy unit="months">15</pregnancy>
            </animal_characteristics>
            <Threats IUCN="Τρωτό" indicat_threat="4">
                <threat threat_id="TH_HAB">Απώλεια Βιότοπου</threat> <!-- ΔΙΟΡΘΩΘΗΚΕ: Προστέθηκε κείμενο και κλείσιμο tag -->
            </Threats>
            <additional_info>
                <trainer_accreditation is_accredited="yes" accredited_trainers="T4"/> <!-- ΔΙΟΡΘΩΘΗΚΕ: T4 αντί για T2 για συνέπεια -->
                <animal_image url="images/giraffe.jpg" type="jpg"/>
                <votes/>
            </additional_info>
        </animal>

        <animal animal_id="A06" an_class_id="K5 C3">
            <animal_names_info animal_name="Κόκκινο Πάντα" scientific_name="Ailurus fulgens"/>
            <trainers trainer_id="T8"/>
            <quantity>2</quantity>
            <animal_descr>Μικρό δενδρόβιο θηλαστικό των Ιμαλαΐων.</animal_descr>
            <animal_characteristics>
                <weight><wmale unit_weight="kg">5</wmale></weight>
                <habitat>Δάση μπαμπού</habitat>
                <dimensions><length unit="m" max="0.6"/></dimensions>
                <lifetime unit="years">10</lifetime>
