=== thanosmp/ZooPark/zoo_park_new.dtd
<!ELEMENT zoo_park (trainer_list, animal_classification, classification, contact_details, park_timings, tickets, animal_list)>
<!ATTLIST zoo_park
    name CDATA #REQUIRED
    number_of_Animals CDATA #REQUIRED
    Year_opened CDATA #REQUIRED>

<!--Λίστα φροντιστών-->
<!ELEMENT trainer_list (trainer+)>
<!ELEMENT trainer EMPTY>
<!ATTLIST trainer 
    trid ID #REQUIRED
    name CDATA #REQUIRED>

<!--Κατηγοριοποίηση ζώων-->
<!ELEMENT animal_classification (classification_type+)>
<!ELEMENT classification_type (#PCDATA)>
<!ATTLIST classification_type 
    classification_id ID #REQUIRED>

<!--Κατηγοριοποίηση ζώων με βάση τη διατροφή και τα μικρά-->
<!ELEMENT classification (class+)>
<!ELEMENT class ((Herbivores | Carnivores | Omnivorous | Wallets | Spawning | Superior)*)>
<!ATTLIST class
    class_id ID #REQUIRED
    value CDATA #REQUIRED>

<!--Καθορισμός id κατηγοριών-->
<!ELEMENT Herbivores EMPTY>
<!ATTLIST Herbivores id CDATA #REQUIRED>
<!ELEMENT Carnivores EMPTY>
<!ATTLIST Carnivores id CDATA #REQUIRED>
<!ELEMENT Omnivorous EMPTY>
<!ATTLIST Omnivorous id CDATA #REQUIRED>
<!ELEMENT Wallets EMPTY>
<!ATTLIST Wallets id CDATA #REQUIRED>
<!ELEMENT Spawning EMPTY>
<!ATTLIST Spawning id CDATA #REQUIRED>
<!ELEMENT Superior EMPTY>
<!ATTLIST Superior id CDATA #REQUIRED>

<!--Στοιχεία επικοινωνίας κήπου-->
<!ELEMENT contact_details (address, tel, email)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT park_timings (Day+)>
<!ELEMENT Day (#PCDATA | Timing)*>
<!ATTLIST Day 
    day_id ID #REQUIRED>
<!ELEMENT Timing (#PCDATA)>

<!ELEMENT tickets (Weekday_Charges, Weekend_Holiday_Charges)>
<!ELEMENT Weekday_Charges (wValue+)>
<!ELEMENT wValue (#PCDATA)>
<!ATTLIST wValue
    ticket_category CDATA #REQUIRED
    unit CDATA #REQUIRED>
<!ELEMENT Weekend_Holiday_Charges (hValue+)>
<!ELEMENT hValue (#PCDATA)>
<!ATTLIST hValue
    ticket_category CDATA #REQUIRED
    unit CDATA #REQUIRED>

<!ELEMENT animal_list (animal+)>

<!ELEMENT animal (animal_names_info, trainers, quantity, animal_descr, animal_characteristics, show_participation?, Threats)>
<!ATTLIST animal
    animal_id ID #REQUIRED
    an_class_id CDATA #REQUIRED>

<!ELEMENT animal_names_info EMPTY>

<!ATTLIST animal_names_info
    animal_name CDATA #REQUIRED
    scientific_name CDATA #IMPLIED>
    
<!ELEMENT trainers EMPTY>
<!ATTLIST trainers 
    trainer_id CDATA #REQUIRED>

<!ELEMENT quantity (#PCDATA)>

<!ELEMENT animal_descr (#PCDATA)>

<!ELEMENT animal_characteristics (allocation, weight, habitat, dimensions, lifetime, (pregnancy | incubation)?, population)>
<!ELEMENT allocation (#PCDATA)>

<!ELEMENT weight (#PCDATA | wmale | wfemale)*>
<!ATTLIST weight 
    unit_weight CDATA #IMPLIED>
<!ELEMENT wmale (#PCDATA)>
<!ATTLIST wmale 
    unit_weight CDATA #REQUIRED>
<!ELEMENT wfemale (#PCDATA)>
<!ATTLIST wfemale 
    unit_weight CDATA #REQUIRED>

<!ELEMENT habitat (#PCDATA)>

<!ELEMENT dimensions (height?, length?)>
<!ELEMENT height (#PCDATA | female)*>
<!ATTLIST height
    unit CDATA #IMPLIED
    max CDATA #IMPLIED
    male CDATA #IMPLIED>
<!ELEMENT length (#PCDATA | female)*>
<!ATTLIST length
    unit CDATA #IMPLIED
    max CDATA #IMPLIED
    male CDATA #IMPLIED>
<!ELEMENT female (#PCDATA)>
<!ATTLIST female
    f_unit_height CDATA #IMPLIED
    f_unit_length CDATA #IMPLIED
    max CDATA #IMPLIED>

<!ELEMENT lifetime (#PCDATA)>
<!ATTLIST lifetime 
    unit CDATA #REQUIRED>

<!ELEMENT pregnancy (#PCDATA)>
<!ATTLIST pregnancy 
    unit CDATA #REQUIRED>

<!ELEMENT incubation (#PCDATA)>
<!ATTLIST incubation 
    unit CDATA #REQUIRED>

<!ELEMENT population (#PCDATA)>

<!ELEMENT show_participation ((feeding | trainer_speaking | show_bird_flight | animal_show)*)>
<!ELEMENT feeding (duration, dates)>
<!ELEMENT trainer_speaking (duration, dates)>
<!ELEMENT show_bird_flight (duration, dates)>
<!ELEMENT animal_show (duration, dates)>

<!ELEMENT duration (#PCDATA)>
<!ATTLIST duration 
    unit CDATA #REQUIRED>

<!ELEMENT dates (date+)>
<!ELEMENT date (#PCDATA)>
<!ATTLIST date
    start_hour CDATA #REQUIRED
    day_id CDATA #REQUIRED>

<!ELEMENT Threats (threat+)>
<!ATTLIST Threats
    IUCN CDATA #REQUIRED
    indicat_threat CDATA #REQUIRED>
<!ELEMENT threat (#PCDATA)>
<!ATTLIST threat 
    threat_id CDATA #REQUIRED>

=== thanosmp/ZooPark/zoo_park_new.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE zoo_park SYSTEM "zoo_park_new.dtd">
<?xml-stylesheet type="text/xsl" href="present1.xsl"?>

<zoo_park name="WILDLIFE XYZ PARK" number_of_Animals="2000" Year_opened="2000">

    <trainer_list>
        <trainer trid="T1" name="George Papadopoulos"/>
        <trainer trid="T2" name="Giannis Nemeas"/>
        <trainer trid="T3" name="Tzina Eleftheriou"/>
        <trainer trid="T4" name="Giorgos Emmanoyilidis"/>
        <trainer trid="T5" name="Rafail Psandimon"/>
        <trainer trid="T6" name="Maria Popova"/>
        <trainer trid="T7" name="Tom Trandon"/>
        <trainer trid="T8" name="Jim Paraskevoglou"/>
        <trainer trid="T9" name="Chris Boris"/>
        <trainer trid="T10" name="Nantia Trejova"/>
        <trainer trid="T11" name="Havie Limon"/>
        <trainer trid="T12" name="Eva Lampanova"/>
    </trainer_list>

    <animal_classification>
        <classification_type classification_id="K1">Αμφίβια</classification_type>
        <classification_type classification_id="K2">Ερπετά</classification_type>
        <classification_type classification_id="K3">Πτηνά</classification_type>
        <classification_type classification_id="K4">Ψάρια</classification_type>
        <classification_type classification_id="K5">Θηλαστικά</classification_type>
    </animal_classification>

    <classification>
        <class class_id="C1" value="diet">
            <Herbivores id="herb"/>
            <Carnivores id="carn"/>
            <Omnivorous id="omni"/>
        </class>

        <class class_id="C2" value="birth">
            <Wallets id="wall"/>
            <Spawning id="spawn"/>
            <Superior id="supe"/>
        </class>
    </classification>

    <contact_details>
        <address>Zoo Park Main Road, XYZ Town, WZY  COUNTRY, 100-45</address>
        <tel>+30 210 23643666</tel>
        <email>xyz@outl.zoopark.com</email>
    </contact_details>

    <park_timings>
        <Day day_id="D1">Δευτέρα - Κλειστά</Day>
        <Day day_id="D2">Τρίτη <Timing>8:00 am – 12:00 pm και 2:00 pm – 5:00 pm</Timing></Day>
        <Day day_id="D3">Τετάρτη <Timing>8:00 am – 5:00 pm</Timing></Day>
        <Day day_id="D4">Πέμπτη <Timing>8:00 am – 12:00 pm και 2:00 pm – 5:00 pm</Timing></Day>
        <Day day_id="D5">Παρασκευή <Timing>8:00 am – 6:00 pm</Timing></Day>
        <Day day_id="D6">Σάββατο <Timing>8:00 am – 7:30 pm</Timing></Day>
        <Day day_id="D7">Κυριακή <Timing>8:00 am – 7:30 pm</Timing></Day>
    </park_timings>

    <tickets>
        <Weekday_Charges>
            <wValue ticket_category="adult" unit="euro">50</wValue>
            <wValue ticket_category="children_3_10" unit="euro">30</wValue>
            <wValue ticket_category="infants_0_2" unit="euro">Δωρεάν</wValue>
        </Weekday_Charges>

        <Weekend_Holiday_Charges>
            <hValue ticket_category="adult" unit="euro">60</hValue>
            <hValue ticket_category="children_3_10" unit="euro">40</hValue>
            <hValue ticket_category="infants_0_2" unit="euro">Δωρεάν</hValue>
        </Weekend_Holiday_Charges>
    </tickets>

    <animal_list>
        <animal animal_id="A1" an_class_id="herb supe K5">
            <animal_names_info animal_name="Άγριο γαϊδούρι της Σομαλίας" scientific_name="Equus asinus somalicus" />
            <trainers trainer_id="T3 T4"/>
            <quantity>10</quantity>
            <animal_descr>Ο αφρικανικός όνος της Σομαλίας (Equus asinus somaliensis) είναι ένα από τα 4 υποείδη αφρικανικού όνου. Ζει στις ερήμους και τις άγονες περιοχές της Σομαλίας, της Αιθιοπίας και της Ερυθραίας. Στην φύση υπάρχουν λιγότερα από 1000 (ή το πολύ 700) άτομα και έχει ταξινομηθεί στα Κρισίμως κινδυνεύοντα (CR) είδη στην Κόκκινη Λίστα των Απειλούμενων Ειδών. Κινδυνεύει κυρίως από το κυνήγι, για το κρέας του και για χρήση στην παραδοσιακή ιατρική. Αυτό το υποείδος ξεχωρίζει από τα άλλα, λόγω των ποδιών του που φέρουν ρίγες σαν της ζέβρας. Τρέφεται κυρίως με φυτά της ερήμου, από χόρτα έως τους αγκαθωτούς θάμνους της ακακίας. Το δυνατό πεπτικό τους σύστημα, τα βοηθάει να παίρνουν επαρκή υγρασία από τις τροφές και έτσι μπορούν να επιβιώσουν χωρίς νερό για αρκετό καιρό. Το υποείδος θεωρείται πρόγονος του κατοικίδιου γαϊδουριού. Ζουν σε βραχώδεις ερήμους, όπου η θερμοκρασία του εδάφους μερικές φορές ξεπερνά τους 50°C. Τα θηλυκά γεννάνε ένα μικρό κάθε 2η χρονιά, μετά από κύηση περίπου 320 ημερών.</animal_descr>
            <animal_characteristics>
                <allocation>Σομαλία, Αιθιοπία, Ερυθραία</allocation>
                <weight unit_weight="kg">280</weight>
                <habitat>Βραχώδεις έρημοι και άγονες περιοχές</habitat>
                <dimensions>
                    <height unit="m" max="true">1.25</height>
                    <length unit="m" max="true">2.05</length>
                </dimensions>
                <lifetime unit="years">30</lifetime>
                <pregnancy unit="days">365</pregnancy>
                <population>600</population>
            </animal_characteristics>
            <show_participation>
                <feeding>
                    <duration unit="minutes">20</duration>
                    <dates>
                        <date start_hour="12:00" day_id="D2">Τρίτη</date>
                        <date start_hour="12:00" day_id="D5">Παρασκευή</date>
                        <date start_hour="13:00" day_id="D7">Κυριακή</date>
                    </dates>
                </feeding>
            </show_participation>
            <Threats IUCN="Κρισίμως Κινδυνεύων" indicat_threat="8">
                <threat threat_id="th1">Κυνήγι για το κρέας του και για χρήση στην παραδοσιακή ιατρική</threat>
                <threat threat_id="th2">Διασταύρωση με τα οικόσιτα γαϊδούρια</threat>
                <threat threat_id="th3">Συνεχόμενοι εμφύλιοι πόλεμοι</threat>
            </Threats>
        </animal>

        <animal animal_id="A2" an_class_id="herb supe K5">
            <animal_names_info animal_name="Ασιατικός Ελέφαντας" scientific_name="Elephas maximus" />
            <trainers trainer_id="T8 T11"/>
            <quantity>7</quantity>
            <animal_descr>Ο ασιατικός ελέφαντας (Elephas maximus) είναι παχύδερμο φυτοφάγο θηλαστικό της τάξης των προβοσκιδωτών. Απαντάται στην Ν. και ΝΑ Ασία, από την Ινδία και το Νεπάλ στα δυτικά έως το Βόρνεο στα νότια. Αναγνωρίζονται τρία υποείδη—το E. m. maximus από τη Σρι Λάνκα, το E. m. indicus από την ηπειρωτική Ασία and το E. m. sumatranus από τη νήσο Σουμάτρα. Οι ασιατικοί ελέφαντες είναι το μεγαλύτερο ζώο που ζει στην Ασία. Ο ασιατικός ελέφαντας ζει σε κοπάδια. Συγγενεύει με τον αφρικανικό ελέφαντα, αλλά έχει πιο μικρά αυτιά, πιο άγριο τρίχωμα και πιο κοντούς χαυλιόδοντες. Εξημερώνεται πιο εύκολα από ότι ο αφρικανικός. Στην Ινδία και την Ταϊλάνδη χρησιμοποιείται ως ζώο μεταφοράς κι εργασίας. Είναι κοινωνικό ζώο με μνήμη που διαρκεί πολύ και ζει σε κοπάδια που τα "διοικεί" ένα ηλικιωμένο θηλυκό. Απειλείται από τη λαθροθηρία.</animal_descr>
            <animal_characteristics>
                <allocation>Απομονωμένα μέρη του Μπαγκλαντές, Μπουτάν, Ινδία, Μυανμάρ, Νεπάλ, Σρι Λάνκα, Ταϋλάνδη, Καμπότζη, Βιετνάμ, Ν. Κίνα, Λάος, Μαλαισία και Ινδονησία.</allocation>
                <weight>
                    <wmale unit_weight="kg">6.000</wmale>
                    <wfemale unit_weight="kg">4.160</wfemale>
                </weight>
                <habitat>Βοσκοτόπια, διάφορα είδη δασών</habitat>
                <dimensions>
                    <height unit="m" max="true">3.40</height>
                    <length unit="m" max="true">6.40</length>
                </dimensions>
                <lifetime unit="years">70</lifetime>
                <pregnancy unit="days">660</pregnancy>
                <population>50.000</population>
            </animal_characteristics>
            <show_participation>
                <trainer_speaking>
                    <duration unit="minutes">30</duration>
                    <dates>
                        <date start_hour="13:30" day_id="D6">Σάββατο</date>
                        <date start_hour="13:30" day_id="D7">Κυριακή</date>
                    </dates>
                </trainer_speaking>
            </show_participation>
            <Threats IUCN="Κινδυνεύων" indicat_threat="7">
                <threat threat_id="th1">Μείωση, υποβάθμιση και κατακερματισμός του βιότοπού τους (λόγω της εξάπλωσης του ανθρώπινου πληθυσμού, που οδηγεί σε σύγκρουση, προκαλώντας τον θάνατο εκατοντάδων ανθρώπων και ελεφάντων ετησίως)</threat>
                <threat threat_id="th2">Κυνήγι για το κρέας και το δέρμα τους</threat>
            </Threats>
        </animal>

        <animal animal_id="A3" an_class_id="carn spawn K2">
            <animal_names_info animal_name="Κροκόδειλος του Νείλου" scientific_name="Crocodylus niloticus" />
            <trainers trainer_id="T10 T11"/>
            <quantity>2</quantity>
            <animal_descr>Ο Κροκόδειλος του Νείλου (επιστημονική ονομασία: Crocodylus niloticus - Κροκόδειλος ο νειλοτικός) είναι ένας κροκόδειλος ο οποίος απαντάται στην Αφρική, από την Σενεγάλη μέχρι την Αίγυπτο και την Νότια Αφρική, ενώ έχουν βρεθεί πληθυσμοί και στην Μαδαγασκάρη. Παλιότερα ζούσε και στο Δέλτα του Νείλου, αλλά σήμερα έχει εξαφανιστεί εκεί. Θεωρείται το δεύτερο μεγαλύτερο κροκοδείλιο που ζει σήμερα μετά τον θαλάσσιο κροκόδειλο, με μήκος που μπορεί να φτάσει μέχρι τα 5,5 μέτρα σε πολύ ηλικιωμένα ζώα και βάρος μέχρι 750 κιλά. Ο μεγαλύτερος που έχει μετρηθεί ήταν ένα αρσενικό στην Τανζανία μήκους 6,47 μέτρων and βάρος 1.090 κιλά.</animal_descr>
            <animal_characteristics>
                <allocation>Υπό-Σαχάρα Αφρική, Μαδαγασκάρη</allocation>
                <weight unit_weight="kg">1.000</weight>
                <habitat>Ποτάμια, βάλτοι γλυκού νερού, εκβολές, μαγκρόβια</habitat>
                <dimensions>
